---
roles:
  - name: robertdebock.bootstrap
  - name: robertdebock.buildtools
  - name: robertdebock.epel
  - name: robertdebock.openssl
  - name: robertdebock.python_pip
  - name: robertdebock.selinux
  - name: robertdebock.httpd
