---
# tasks file for selinux
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install required packages
  package:
    name: "{{ selinux_requirements }}"
    state: present

- name: manage selinux
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  notify:
    - reboot
  when:
    - ansible_selinux.status is defined
    - ansible_connection != "docker"

- name: manage selinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state | default('yes') }}"
    persistent: "{{ item.persistent }}"
  loop: "{{ selinux_booleans }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_selinux.status is defined
    - ansible_connection != "docker"
    - selinux_booleans is defined
